/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */
declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }

  interface HTMLAttributes {}
}


import {
  Auth0Authenticate as Auth0Authenticate
} from './components/auth0-authenticate/auth0-authenticate';

declare global {
  interface HTMLAuth0AuthenticateElement extends Auth0Authenticate, HTMLStencilElement {
  }
  var HTMLAuth0AuthenticateElement: {
    prototype: HTMLAuth0AuthenticateElement;
    new (): HTMLAuth0AuthenticateElement;
  };
  interface HTMLElementTagNameMap {
    "auth0-authenticate": HTMLAuth0AuthenticateElement;
  }
  interface ElementTagNameMap {
    "auth0-authenticate": HTMLAuth0AuthenticateElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "auth0-authenticate": JSXElements.Auth0AuthenticateAttributes;
    }
  }
  namespace JSXElements {
    export interface Auth0AuthenticateAttributes extends HTMLAttributes {
      clientId?: string;
      domain?: string;
      popup?: boolean;
      redirectUri?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
