/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Auth0Authenticate {
        "clientId": string;
        "domain": string;
        "getApiAccessToken": (audience: string, scopes: string) => Promise<{ accessToken: string; }>;
        "getUser": () => Promise<any>;
        "isAuthenticated": () => Promise<any>;
        "login": () => Promise<any>;
        "logout": () => Promise<any>;
        "popup": boolean;
        "redirectUri": string;
    }
}
declare global {
    interface HTMLAuth0AuthenticateElement extends Components.Auth0Authenticate, HTMLStencilElement {
    }
    var HTMLAuth0AuthenticateElement: {
        prototype: HTMLAuth0AuthenticateElement;
        new (): HTMLAuth0AuthenticateElement;
    };
    interface HTMLElementTagNameMap {
        "auth0-authenticate": HTMLAuth0AuthenticateElement;
    }
}
declare namespace LocalJSX {
    interface Auth0Authenticate {
        "clientId"?: string;
        "domain"?: string;
        "popup"?: boolean;
        "redirectUri"?: string;
    }
    interface IntrinsicElements {
        "auth0-authenticate": Auth0Authenticate;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "auth0-authenticate": LocalJSX.Auth0Authenticate & JSXBase.HTMLAttributes<HTMLAuth0AuthenticateElement>;
        }
    }
}
